ARG ARCH='x86_64'
ARG RHEL_VERSION='9.2'
ARG KERNEL_VERSION='5.14.0-284.43.1.el9_2'
ARG BASE_DIGEST=''
#FROM registry.distributed-ci.io/dtk/driver-toolkit:${KERNEL_VERSION} as builder 
FROM quay.io/ebelarte/driver-toolkit:5.14.0-284.40.1.el9_2 as builder

ARG ARCH='x86_64'
ARG DRIVER_VERSION='535.104.05'
ARG DRIVER_EPOCH='1'
ARG KERNEL_VERSION='5.14.0-284.43.1.el9_2'
ARG RHEL_VERSION='9.2'

WORKDIR /home/builder
COPY kmod-nvidia.spec kmod-nvidia.spec

RUN export KVER=$(echo ${KERNEL_VERSION} | cut -d '-' -f 1) \
        KREL=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/\.el._.$//') \
        KDIST=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/^.*\(\.el._.\)$/\1/') \
        DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) \
    && mkdir yum-packaging-precompiled-kmod \ 
    && cd yum-packaging-precompiled-kmod \
    && mkdir BUILD BUILDROOT RPMS SRPMS SOURCES SPECS \
    && mkdir nvidia-kmod-${DRIVER_VERSION}-${ARCH} \
    && git clone -b ${DRIVER_VERSION}  https://github.com/NVIDIA/open-gpu-kernel-modules.git \
    && mv open-gpu-kernel-modules/* nvidia-kmod-${DRIVER_VERSION}-${ARCH}/ \
    && tar -cJf SOURCES/nvidia-kmod-${DRIVER_VERSION}-${ARCH}.tar.xz nvidia-kmod-${DRIVER_VERSION}-${ARCH} \
    && mv ../kmod-nvidia.spec SPECS/ \
    && rpmbuild \
        --define "%_topdir $(pwd)" \
        --define "debug_package %{nil}" \
        --define "kernel ${KVER}" \
        --define "kernel_release ${KREL}" \
        --define "kernel_dist ${KDIST}" \
        --define "driver ${DRIVER_VERSION}" \
        --define "epoch ${DRIVER_EPOCH}" \
        --define "driver_branch ${DRIVER_STREAM}" \
        -v -bb SPECS/kmod-nvidia.spec

